### ISSUE TITLE
Schema update conflicts (Bug when using)

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#126]
```
[SQL: SELECT points.uuid AS points_uuid, points.name AS points_name, points.device_uuid AS points_device_uuid, points.enable AS points_enable, points.history_enable AS points_history_enable, points.history_type AS points_history_type, points.history_interval AS points_history_interval, points.cov_threshold AS points_cov_threshold, points.writable AS points_writable, points.write_value AS points_write_value, points.driver AS points_driver, points.created_on AS points_created_on, points.updated_on AS points_updated_on, point_stores_1.point_uuid AS point_stores_1_point_uuid, point_stores_1.value AS point_stores_1_value, point_stores_1.value_array AS point_stores_1_value_array, point_stores_1.fault AS point_stores_1_fault, point_stores_1.fault_message AS point_stores_1_fault_message, point_stores_1.ts AS point_stores_1_ts 
FROM points LEFT OUTER JOIN point_stores AS point_stores_1 ON points.uuid = point_stores_1.point_uuid 
WHERE ? = points.device_uuid]
[parameters: ('ce7b5f4b-79dc-48dc-b74e-d44e9e1453f9',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2020-11-30 19:34:53,079 INFO: werkzeug> 49.180.47.223 - - [30/Nov/2020 19:34:53] "GET /api/modbus/networks HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: points.cov_threshold

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 680, in wrapper
    return marshal(resp, self.fields, self.envelope)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 631, in marshal
    if envelope else [marshal(d, fields) for d in data])
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 630, in <listcomp>
    return (OrderedDict([(envelope, [marshal(d, fields) for d in data])])
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 200, in output
    return self.format(value)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 193, in format
    for idx, val in enumerate(value)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 193, in <listcomp>
    for idx, val in enumerate(value)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 155, in output
    return marshal(value, self.nested)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 636, in marshal
    return OrderedDict([(envelope, OrderedDict(items))]) if envelope else OrderedDict(items)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 635, in <genexpr>
    for k, v in fields.items())
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 197, in output
    value = get_value(key if self.attribute is None else self.attribute, data)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 43, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 48, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/flask_restful/fields.py", line 60, in _get_value_for_key
    return getattr(obj, key, default)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
    value = self.callable_(state, passive)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 760, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
    
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/orm/strategies.py", line 902, in _emit_lazyload
    .with_post_criteria(set_default_params)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 544, in all
    return list(self)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/ext/baked.py", line 444, in __iter__
    return q._execute_and_instances(context)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/common-py-libs/venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: points.cov_threshold
[SQL: SELECT points.uuid AS points_uuid, points.name AS points_name, points.device_uuid AS points_device_uuid, points.enable AS points_enable, points.history_enable AS points_history_enable, points.history_type AS points_history_type, points.history_interval AS points_history_interval, points.cov_threshold AS points_cov_threshold, points.writable AS points_writable, points.write_value AS points_write_value, points.driver AS points_driver, points.created_on AS points_created_on, points.updated_on AS points_updated_on, point_stores_1.point_uuid AS point_stores_1_point_uuid, point_stores_1.value AS point_stores_1_value, point_stores_1.value_array AS point_stores_1_value_array, point_stores_1.fault AS point_stores_1_fault, point_stores_1.fault_message AS point_stores_1_fault_message, point_stores_1.ts AS point_stores_1_ts 
FROM points LEFT OUTER JOIN point_stores AS point_stores_1 ON points.uuid = point_stores_1.point_uuid 
WHERE ? = points.device_uuid]
[parameters: ('ce7b5f4b-79dc-48dc-b74e-d44e9e1453f9',)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

```

**Comment by RaiBnod** [comment]
Seems like the database contain old table schema. Recently we have added that `cov_threshold` may be that lead this issue. Currently, if that is the case we need to delete old db and create new one. On the meantime I will look on the migration task for such cases.
