### ISSUE TITLE
This error stopped the modbus polling for working

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-point-server#181]
```
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]: Traceback (most recent call last):
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "threading.py", line 954, in _bootstrap_inner
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/background.py", line 23, in run
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "threading.py", line 892, in run
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/source_drivers/modbus/services/modbus_polling.py", line 39, in polling
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/source_drivers/modbus/services/modbus_polling.py", line 85, in __poll
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/source_drivers/modbus/services/modbus_polling.py", line 134, in __poll_point
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/source_drivers/modbus/services/modbus_functions/polling/poll.py", line 96, in poll_point
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]:   File "src/source_drivers/modbus/services/modbus_functions/polling/functions.py", line 133, in write_analogue
Jan 18 10:03:18 raspberrypi rubix-point-server[4202]: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Comment by Shiny380** [comment]
can you possibly do a GET req for that point and post the JSON?
