### ISSUE TITLE
Issue: Too many open files

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-point-server#448]
```
Jul 13 23:46:34 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:34,786 INFO: gunicorn.access> 127.0.0.1 - - [13/Jul/2023:23:46:34 +1000] "PATCH /api/generic/points_value/name/WPCC/Ahu-01-Zn-03-Pre-Hum/Enthalpy HTTP/1.1" 200 3 "-" "axios/0.21.1"
Jul 13 23:46:34 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:34,844 INFO: gunicorn.access> 127.0.0.1 - - [13/Jul/2023:23:46:34 +1000] "PATCH /api/generic/points_value/name/WPCC/Ahu-02/Z1-Heating-demand HTTP/1.1" 400 44 "-" "axios/0.21.1"
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:35,820 INFO: src.services.histories.history_local> HistoryLocal > sync_interval is started...
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:35,830 ERROR: src.handlers.exception> __sync_interval> (sqlite3.OperationalError) unable to open database file
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: (Background on this error at: https://sqlalche.me/e/14/e3q8)
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: Traceback (most recent call last):
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]:   File "gevent/baseserver.py", line 227, in _do_read
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]:   File "gevent/server.py", line 198, in do_read
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: OSError: [Errno 24] Too many open files
Jul 13 23:46:35 raspberrypi rubix-point-server[26456]: 2023-07-13T13:46:35Z <StreamServer at 0x724a7340 fileno=7 address=0.0.0.0:1515 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0x74f72328>>, <gevent._socket3.socket at 0x74a742f8 object, fd=7, family=2, type=1, proto=6>)> failed with OSError
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]: Traceback (most recent call last):
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]:   File "gevent/baseserver.py", line 227, in _do_read
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]:   File "gevent/server.py", line 198, in do_read
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]: OSError: [Errno 24] Too many open files
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]: 2023-07-13T13:46:36Z <StreamServer at 0x724a7340 fileno=7 address=0.0.0.0:1515 handle=functools.partial(<bound method GeventWorker.handle of <gunicorn.workers.ggevent.GeventWorker object at 0x74f72328>>, <gevent._socket3.socket at 0x74a742f8 object, fd=7, family=2, type=1, proto=6>)> failed with OSError
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:36,633 INFO: gunicorn.access> 127.0.0.1 - - [13/Jul/2023:23:46:36 +1000] "PATCH /api/generic/points_value/uuid/BUz33BxpyCWKgagQWeT84S HTTP/1.1" 200 3 "-" "python-requests/2.25.1"
Jul 13 23:46:36 raspberrypi rubix-point-server[26456]: 2023-07-13 23:46:36,671 INFO: gunicorn.access> 127.0.0.1 - - [13/Jul/2023:23:46:36 +1000] "PATCH /api/generic/points_value/uuid/Xw4oXn6vxRFHJmkorr6jJb HTTP/1.1" 200 3 "-" "python-requests/2.25.1"
```

**Comment by RaiBnod** [comment]
It was because the interval records creation on 10s was taking time and at the same time we were doing lots of API calls as well.
